"""empty message

Revision ID: 089da532746d
Revises: 
Create Date: 2021-05-21 12:49:58.748605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089da532746d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=160), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_model')
    # ### end Alembic commands ###
